---
- name: Configure webserver with apache
  hosts: p2p
  become: True

  tasks:
    - name: Install apache2
      apt: name=apache2 update_cache=yes cache_valid_time=3600

    - name: copy apache config file
      copy: src=apache2.conf dest=/etc/apache2/apache2.conf

    - name: allow apache2 access through firewall
      ufw: rule=allow direction=in name="Apache Full"

    - name: copy index
      copy: src=index.html dest=/var/www/html/
    - name: copy assets
      copy: src=assets dest=/var/www/html/
    - name: copy images
      copy: src=images dest=/var/www/html/
    - name: copy posts
      copy: src=posts dest=/var/www/html/


    - name: restart apache2
      service: name=apache2 state=restarted
