---
- name: Configure webserver with apache
  hosts: webservers  # "{{ env_host }}"
  become: True

  tasks:
    - name: Install apache2
      dnf: name={{ item }} state=latest
      with_items:
        - httpd
        - python3-pip
    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: add http and https
      firewalld: service={{ item }} permanent=true state=enabled immediate=yes zone=FedoraServer
      with_items:
        - http
        - https

    - name: Start http daemon
      systemd: state=started name=httpd
    # - name: open public http ports
    #   firewalld: port=80/tcp zone=public permanent=true state=enabled immediate=yes
    # - name: open public https ports
    #   firewalld: port=443/tcp zone=public permanent=true state=enabled immediate=yes


    # - name: copy apache config file
    #   copy: src=apache2.conf dest=/etc/apache2/apache2.conf
    # - name: copy Apache config file for app
    #   copy: src=p2p.conf dest=/etc/apache2/sites-available/
    - name: enable virtualhost for app
      shell: a2ensite p2p

    - name: allow apache2 access through firewall
      ufw: rule=allow direction=in name="Apache Full"

    - name: copy Flask app
      copy: src=p2p/ dest=/var/www/p2p/p2p/
    - name: copy p2p.wsgi
      copy: src=p2p.wsgi dest=/var/www/p2p/
    - name: copy requirements
      copy: src=requirements.txt dest=/var/www/p2p/

    - name: Create virtual environment
      pip:
        requirements: /var/www/p2p/requirements.txt
        virtualenv: /var/www/p2p/p2p/p2p_venv
        virtualenv_python: python3

    - name: restart apache2
      service: name=apache2 state=restarted

    # - name: Start flask app
    #   shell: /var/www/html/p2p_venv/bin/python3.4 /var/www/html/p2p.py
